### ISSUE TITLE
Prepare for meeting with Julian

### ISSUE THREAD

**Issue by japarra** [asu-cis440-summer/studiocracy-development-cnprt#14]
Read the requirements spec
Look over the Studiocracy README
List any of your questions

**Comment by japarra** [comment]
Read the requirements spec
Look over the Studiocracy README

**Comment by jcnguye2** [comment]
What is this table "Post" for? Are we collecting info from all these attributes or 
we are responsible for the functionality?

What kind of questions should we ask about artist? (exe: category of art? years of experience? photos of art work?)

Can we simplify the procedure of registration process by our reference? Or should we follow the instructions?

**Comment by japarra** [comment]
Is each uploaded piece of work required to be posted for sale?

Do artists have the opportunity to post their work for sale during the registration process?

In what specific areas is our help wanted? UI & UX suggestions? Coding the designs?
