### ISSUE TITLE
List our skillsets

### ISSUE THREAD

**Issue by japarra** [asu-cis440-summer/studiocracy-development-cnprt#15]
Make a comment with skills you have to offer for this project. This is something Julian wants to talk about to set expectations for us.

**Comment by japarra** [comment]
HTML
CSS
Javascript/JQuery
Bootstrap
Ruby on Rails
Git/Github

**Comment by dannbaman** [comment]
HTML
CSS
Javascript/JQuery
Bootstrap

**Comment by jcnguye2** [comment]
HTML
CSS
JavaScript/JQuery
PHP (not too much)
Ruby (just a scratch)

**Comment by colinruane** [comment]
HTML
CSS
JavaScript
Ruby

**Comment by dcannan** [comment]
HTML
CSS
JavaScript/JQuery
PHP
Ruby
MySQL
