### ISSUE TITLE
Compile a list of beginner rails resources

### ISSUE THREAD

**Issue by japarra** [asu-cis440-summer/studiocracy-development-cnprt#16]
It might be necessary that everybody on the team learn the basics of rails. I'm not sure if it is feasible for me to implement your changes into the rails app. I could probably better spend my time developing features myself. The main points to learn about rails is how it implements the MVC design pattern and how it dynamically constructs the html, css, and js files for delivery to the browser.

**Comment by japarra** [comment]
Here is a popular tutorial for beginners in web development. I haven't taken the tutorial myself, but people on the internet hold this tutorial in high esteem. You may want to just skip to the section on Ruby on Rails.

http://www.theodinproject.com/courses?ref=home

**Comment by japarra** [comment]
I learned rails first from Michael Hartl's online book called [Ruby on Rails Tutorial](https://www.railstutorial.org/book). It may take too long to teach you what you need to know though.

Again here's the link: 

https://www.railstutorial.org/book

**Comment by japarra** [comment]
Here is a third resource and this one is really good. I came across this book a few months ago and does a *really really* great job of explaining rails in lay men's terms. 

https://drive.google.com/file/d/0B8dyTUAKdOOyUWV6WkNaOG5NSnM/view?usp=sharing

**Comment by japarra** [comment]
I'll just leave this tutorial here too. This is an interactive tutorial that takes you step-by-step into building a rails app. I haven't taken it, but it looks promising and it's popular on this rails forum (i.e. the rails subreddit).

http://www.codelearn.org/

**Comment by dcannan** [comment]
Here is a page from rails guides that talks about the route file:
http://guides.rubyonrails.org/routing.html

**Comment by japarra** [comment]
Oh and @dcannan the description wasn't directed at you. I had told the rest of the team that I would implement what they had into rails.

**Comment by dcannan** [comment]
Here is a tutorial I used a while ago, that has you build a simple blog with rails:
http://guides.rubyonrails.org/getting_started.html
