### ISSUE TITLE
List instructions on README for how to set up app in a dev environment

### ISSUE THREAD

**Issue by japarra** [asu-cis440-summer/studiocracy-development-cnprt#19]
Instructions are listed on the How to Contribute section of Studiocracy's README

https://github.com/Studiocracy/studiocracy-public/blob/master/README.md

**Comment by dcannan** [comment]
Are you saying we should put this on OUR readme, or are you just pointing out that it is in the studiocracy readme file?

**Comment by japarra** [comment]
We would at least have a link on our README that links to the google doc with the setup instructions that Studiocracy posted on their README.

We have a couple to choose from:

https://docs.google.com/document/d/1Iz6dZUZajbmrXTQJi7UUr5DE8zuyPRtfWt_Yc-g2H24/edit

https://drive.google.com/folderview?id=0BxTarWOIystqflByWkkzSy1VQTNUS2xpT2JsUWlxTThQdVpFdHdRWUdqVXNadHdab0dXQVk&usp=sharing

**Comment by japarra** [comment]
I need to ask Sopha if it is sufficient to just put a link to their set up instructions on our README. It seems like a bit of a cop-out.

**Comment by dcannan** [comment]
If we can, I think we should post both.  The first is for setting it up like you did, and the 2nd is great for people setting up a local dev environment

**Comment by japarra** [comment]
You're right. Ok, I emailed sopha and I cc'd you and the rest of the team.

**Comment by dcannan** [comment]
OK, if he says it is not OK, then we'll figure out what to do from there.
