### ISSUE TITLE
Pick a theme for the slide deck

### ISSUE THREAD

**Issue by japarra** [asu-cis440-summer/studiocracy-development-cnprt#23]
Pick a theme for the slide deck on Google Slides that we will use for our Bootstrap Tech Talk.

**Comment by japarra** [comment]
Below is the theme that I selected: 

http://www.slidescarnival.com/perdita-free-presentation-template/351

Below is our Google Slide deck: 

https://docs.google.com/presentation/d/1wo-Q5R1yPrPhatMBO1TwyDPDtFWjuroj1twpPeTJTFs/edit#slide=id.g35f391192_00

I changed the color to purple because boostrap's (website)[http://getbootstrap.com/] uses that color.

**Comment by dcannan** [comment]
I like it
