### ISSUE TITLE
Determine the Tech Stack for Studiocracy app

### ISSUE THREAD

**Issue by japarra** [asu-cis440-summer/studiocracy-development-cnprt#25]

**Comment by japarra** [comment]
OS - Linux
Web Server - Unicorn
DBMS - PostgreSQL
Programming Language - Ruby 2.2.1
(?) - Ruby on Rails 4.2.0

(Do we need to include into our tech stack?)
HTML/CSS/JS
Bootstrap
JQuery

How do we define the OS component of the tech stack? Do we only include the OS that is used in the production environment? I'm assuming Linux will be the OS they use in production.

**Comment by japarra** [comment]
Do we even need to write this out on our README?

**Comment by japarra** [comment]
Actually I'm erring on the side of let's not list their stack is at all. We can just include Studiocracy's  docs on how to set up an environment to run their app.

**Comment by japarra** [comment]
I emailed Sopha.

**Comment by dcannan** [comment]
I think we should put what we have, and if we know what exact version of
linux, that would be better

**Comment by japarra** [comment]
I was thinking if we included the tech stack, it would only describe the tech stack used in their production environment.

**Comment by japarra** [comment]
We'll get an official answer soon from Sopha. I forgot to cc you guys in it though.
