### ISSUE TITLE
Set up appointment with Studiocracy

### ISSUE THREAD

**Issue by japarra** [asu-cis440-summer/studiocracy-development-cnprt#7]

**Comment by japarra** [comment]
We will have a meeting via Google Hangouts with Julian on Wed (7/15) sometime between 4:30 and 7. He will have to leave the call at 7 to join another call with the Studiocracy team. Let's try to start this call before 6:15 to make sure we are cut off short.

**Comment by japarra** [comment]
We just need to finalize a time that works for all of us.

**Comment by dannbaman** [comment]
5pm works for me
